---
# SIP network interface names
ext_name: ilab
bdn_name: p3-bdn
lln_name: p3-lln

# SIP configuration
cluster_user: "fedora"
cluster_name: "k8s-demo"
cluster_template_name: "k8s-fedora-atomic-29"
cluster_keypair: "wendy"
cluster_coe: "kubernetes"
cluster_default_interface: "{{ ext_name }}"
cluster_interfaces:
- "{{ ext_name }}"
- "{{ lln_name }}"
- "{{ bdn_name }}"

cluster_master_group:
  name: "master"
  count: 1

cluster_worker_group:
  name: "minion"
  count: 1

cluster_groups:
- "{{ cluster_master_group }}"
- "{{ cluster_worker_group }}"

cluster_roles:
- name: "kubernetes"
  groups: "{{ cluster_groups }}"
- name: "ceph_client"
  groups: "{{ cluster_groups }}"

# Kubernetes version
cluster_k8s_version: "v1.14.1"
cluster_k8s_master_kubelet: true

# Manila mount config
ceph_mount_enabled: true
ceph_mount_fuse: false

# Override alaska_homedir as Fedora Atomic doesn't allow folders to be created under root scope
alaska_homedir: "/mnt/alaska"

# Disable these before running setup.yml
kdump_enable: false
# This is enabled by default on Atomic Host
setup_time_enable: false

# The user is fedora for Kubernetes and Docker Swarm container clusters.
alaska_admin_user: fedora
...
