---
- src: stackhpc.cluster-infra
  version: v18.11.9
- src: stackhpc.os-container-infra
  version: v19.6.1
- src: stackhpc.os-manila-mount
  version: v19.1.1
- src: stackhpc.beegfs
  version: v19.4.1
- src: stackhpc.monasca-agent
- src: stackhpc.monasca-rsyslog
- src: stackhpc.grafana-conf
- src: stackhpc.gluster-cluster
- src: stackhpc.os-config
- src: singleplatform-eng.users
- src: mrlesmithjr.mdadm
- src: oasis_roles.kdump
...
