---
# Sorted by maintainer name, role name
- src: mrlesmithjr.mdadm
- src: oasis_roles.kdump
- src: singleplatform-eng.users
- src: stackhpc.cluster-infra
  version: v20.2.0
- src: stackhpc.os-container-infra
  version: v20.0.0
- src: stackhpc.os-manila-mount
  version: v19.6.1
- src: stackhpc.beegfs
  version: v19.8.2
- src: stackhpc.monasca-agent
- src: stackhpc.monasca-rsyslog
- src: stackhpc.grafana-conf
- src: stackhpc.gluster-cluster
- src: stackhpc.openhpc
  version: v0.4.0
- src: stackhpc.os-config
...
